apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: roboshop
  labels:
    purpose: service_demo
    project: roboshop
    tier: database
spec:
  selector:
    component: mongodb
    project: roboshop
    tier: database
  clusterIP: None  # This makes the service headless
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    component: mongodb-service
spec:
  selector:
    component: mongodb
    project: roboshop
    tier: database
  ports:  
  - protocol: TCP
    port: 27017
    targetPort: 27017

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    matchLabels:
      component: mongodb
      project: roboshop
      tier: database # has to match .spec.template.metadata.labels
  serviceName: "mongodb-headless"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        component: mongodb
        project: roboshop
        tier: database # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mongodb
        image: yadaveshnithin/mongodb:v1
        volumeMounts:
        - name: mongodb_data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb_data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc-roboshop"
      resources:
        requests:
          storage: 2Gi



          